[pytest]
DJANGO_SETTINGS_MODULE = zentra.settings.dev
python_files = tests/*.py tests/**/*.py
addopts = --strict-markers -v --tb=short --cov=apps --cov-report=term-missing
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
