# Generated by Django 6.0.3 on 2026-03-10 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Legal registered name if different', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='PNG logo, recommended 400×160 px (retina: 800×320 px), max 2 MB', null=True, upload_to='organizations/logos/')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-selected when creating new documents; only one org can be default')),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='VAT / GST / Tax ID', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='Company registration / ABN / EIN', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_sort_code', models.CharField(blank=True, help_text='Routing number / Sort code / BSB', max_length=100)),
                ('bank_swift_iban', models.CharField(blank=True, help_text='SWIFT / BIC / IBAN', max_length=100)),
                ('bank_instructions', models.TextField(blank=True, help_text='Additional payment instructions shown on invoices')),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('quote_prefix', models.CharField(default='QUO', max_length=10)),
                ('default_invoice_notes', models.TextField(blank=True)),
                ('default_invoice_terms', models.TextField(blank=True)),
                ('default_retainer_notes', models.TextField(blank=True)),
                ('default_retainer_terms', models.TextField(blank=True)),
                ('default_credit_note_notes', models.TextField(blank=True)),
                ('default_credit_note_terms', models.TextField(blank=True)),
                ('default_receipt_notes', models.TextField(blank=True)),
                ('default_receipt_terms', models.TextField(blank=True)),
                ('default_quote_notes', models.TextField(blank=True)),
                ('default_quote_terms', models.TextField(blank=True)),
                ('default_report_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
