# Generated by Django 6.0.3 on 2026-03-10 04:24

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='service', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('unit_of_measure', models.CharField(choices=[('unit', 'Unit'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('kg', 'Kilogram'), ('lb', 'Pound'), ('meter', 'Meter'), ('liter', 'Liter')], default='unit', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as a percentage (e.g. 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['name'],
            },
        ),
    ]
