# Generated by Django 6.0.3 on 2026-03-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('items', '0002_initial'),
        ('organizations', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='items.item'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['number'], name='quotes_number_37a71f_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_status_b396a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='quotes_custome_cc5ace_idx'),
        ),
    ]
