# Generated by Django 6.0.3 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes/pdf/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
